# Generated by Django 6.0.2 on 2026-02-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADA', 'Emprestada'), ('MANUTENCAO', 'Manutenção')], default='DISPONIVEL', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
                'db_table': 'chave',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('tipo_vinculo', models.CharField(choices=[('SERVIDOR', 'Servidor'), ('TERCEIRIZADO', 'Terceirizado'), ('ESTAGIARIO', 'Estagiário'), ('VISITANTE', 'Visitante')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'db_table': 'setor',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('chave', models.ForeignKey(db_column='chave_id', on_delete=django.db.models.deletion.RESTRICT, related_name='emprestimos', to='app.chave')),
                ('pessoa', models.ForeignKey(db_column='pessoa_id', on_delete=django.db.models.deletion.RESTRICT, related_name='emprestimos', to='app.pessoa')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'db_table': 'emprestimo',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='setor',
            field=models.ForeignKey(blank=True, db_column='setor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='app.setor'),
        ),
    ]
