# Generated by Django 6.0.2 on 2026-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_vinculo',
            field=models.CharField(choices=[('SERVIDOR', 'Servidor'), ('TERCEIRIZADO', 'Terceirizado')], max_length=20),
        ),
    ]
