# Generated by Django 6.0.2 on 2026-03-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chave_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
