version: '3.8'

services:
  database:
    image: postgres:15-alpine # Imagem oficial e leve do PostgreSQL
    container_name: sischave_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT_LOCAL}:${DB_PORT_CONTAINER}"
    volumes:
      - db_data:/var/lib/postgresql/data # Caminho oficial de persistência do Postgres
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sischave_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sischave_backend
    restart: unless-stopped
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate --fake-initial &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8080:8000"  # AQUI ESTÁ O SEGREDO: A porta 8080 externa aponta para a 8000 interna
    environment:
      - DB_HOST=database
      - DB_PORT=${DB_PORT_CONTAINER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${SECRET_KEY}
    depends_on:
      - database
    networks:
      - sischave_network

  # FRONTEND COMENTADO TEMPORARIAMENTE PARA NÃO QUEBRAR O BUILD
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: sischave_frontend
  #   restart: unless-stopped
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "${WEB_PORT}:${WEB_PORT}"
  #   environment:
  #     - API_BASE_URL=http://localhost:${API_PORT}
  #   depends_on:
  #     - backend
  #   networks:
  #     - sischave_network

networks:
  sischave_network:
    driver: bridge

volumes:
  db_data: